name: Image Analysis with Anthropic's Claude LLM
description: Transcription and Information Extraction from Images with Anthropic Claude
author: Cloudera, Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2024-10-01"

environment_variables:
  ANTHROPIC_API_KEY:
    default: ""
    description: "Anthropic API key for Claude access."
    required: true

runtimes:
  - editor: JupyterLab
    kernel: Python 3.11 
    edition: Standard 

tasks:
  - type: run_session
    name: Install Dependencies
    script: 1_session-install-dependencies/download_requirements.py
    short_summary: Install Requirements and Dependencies
    kernel: python3
    cpu: 2
    memory: 8

  - type: start_application
    name: Anthropic Claude Image Analysis
    subdomain: anthropic-claude
    script: 2_application/start-app.py
    short_summary: Streamlit application for image analysis with Anthropic's Claude LLM
    long_summary: Streamlit application for image analysis including extraction, transcription and summarization with Anthropic's Claude LLM
    cpu: 2
    memory: 8
    environment_variables:
      TASK_TYPE: START_APPLICATION