name: Document Summarization with Gemini from Vertex AI
description: Summarize documents and text using Google's Gemini models from the Vertex AI Model Garden. Suggested runtime is JupyterLab, Python 3.11, Standard Edition with lastest version.
author: Cloudera, Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2024-09-29"

environment_variables:
  GOOGLE_API_KEY:
    default: ""
    description: "Google API Key with access to Gemini models"
    required: true

runtimes:
  - editor: JupyterLab
    kernel: Python 3.11
    edition: Standard ## NO GPU required since API access to Vertex AI is sufficient

tasks:
  - type: run_session
    name: Install Dependencies
    script: 1_session-install-dependencies/download_requirements.py
    short_summary: Install Requirements and Dependencies
    kernel: python3
    cpu: 2
    memory: 8

  - type: create_job
    name: Load Documents in docs folder to LlamaIndex vector store
    entity_label: load-docs
    script: 2_job_load-to-vector-db/load-to-vector-db.py
    arguments: None
    cpu: 2
    memory: 8
    short_summary: Load Documents in docs folder to LlamaIndex vector store (creates embeddings from docs)
    environment:
      TASK_TYPE: CREATE/RUN_JOB

  - type: run_job
    entity_label: load-docs
    short_summary: Load Documents in docs folder to LlamaIndex vector store (creates embeddings from docs)

  - type: start_application
    name: Doc Summarization with Gemini
    subdomain: vertex-ai-gemini
    script: 3_application/start-app.py
    short_summary: Launch streamlit UI for document summarization with Google's Gemini models
    long_summary: Launch streamlit UI for document summarization with Google's Gemini models
    cpu: 2
    memory: 8
    environment_variables:
      TASK_TYPE: START_APPLICATION
